require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest

AllCops:
  Exclude:
    - bin/**/*
    - db/schema.rb
    - db/migrate/*.rb
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
    - .pryrc
    - Rakefile
    - .env
  DisplayStyleGuide: true
  ExtraDetails: true
  NewCops: enable
  TargetRubyVersion: 3.0

Style/Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false

Style/RegexpLiteral:
  Description: "Use `//` around regular expression. (https://rubystyle.guide#percent-r)"
  Enabled: false

Metrics/MethodLength:
  Description: "Method has too many lines. [12/10]"
  Enabled: false
